# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: akmp1611/booking-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DB_NAME
              value: "booking"
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              value: "Ak556655^"
            - name: DB_HOST
              value: "booking.crcoc80imb9a.ap-southeast-1.rds.amazonaws.com"
            - name: DB_DIALECT
              value: "mysql"
---
# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000 # Port accessible inside the cluster
      targetPort: 5000 # Port where the container is listening
  type: ClusterIP # Use LoadBalancer if you want it accessible externally
