version: "3.8"

services:
  # MySQL Database Service
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: booking
      MYSQL_USER: admin
      MYSQL_PASSWORD: Ak556655^
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Node.js Application Service
  app:
    build: .
    container_name: booking_app
    environment:
      PORT: 5000
      DB_NAME: booking
      DB_USER: admin
      DB_PASSWORD: Ak556655^
      DB_HOST: mysql
      DB_DIALECT: mysql
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app

volumes:
  mysql_data:
