# mongo-externalname.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-external
  namespace: default
  labels:
    app: mongo-external-service
spec:
  type: ExternalName
  externalName: booking.johpv.mongodb.net
